<?php

namespace Cooper\FilamentDcatFilters\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class FilterMatrixCommand extends Command
{
    protected $signature = 'dcat-filters:matrix
                            {--format=markdown : Output format (markdown or json)}
                            {--output= : Write to file instead of stdout}';

    protected $description = 'Generate a capability matrix for all Dcat filters';

    public function handle(): int
    {
        $filters = $this->discoverFilters();
        $matrix = $this->buildMatrix($filters);

        $format = $this->option('format');
        $output = $format === 'json'
            ? json_encode($matrix, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)
            : $this->formatMarkdown($matrix);

        $outputPath = $this->option('output');

        if ($outputPath) {
            File::ensureDirectoryExists(dirname($outputPath));
            File::put($outputPath, $output);
            $this->info("Matrix written to {$outputPath}");
        } else {
            $this->line($output);
        }

        return self::SUCCESS;
    }

    protected function discoverFilters(): array
    {
        $filterDir = dirname(__DIR__).'/Filters';
        $filters = [];

        foreach (File::files($filterDir) as $file) {
            $className = 'Cooper\\FilamentDcatFilters\\Filters\\'.pathinfo($file->getFilename(), PATHINFO_FILENAME);

            if (! class_exists($className)) {
                continue;
            }

            $reflection = new \ReflectionClass($className);

            if ($reflection->isAbstract() || ! $reflection->isSubclassOf(\Filament\Tables\Filters\Filter::class)) {
                continue;
            }

            $filters[] = $className;
        }

        sort($filters);

        return $filters;
    }

    protected function buildMatrix(array $filterClasses): array
    {
        $matrix = [];

        foreach ($filterClasses as $className) {
            $shortName = class_basename($className);

            try {
                $filter = $className::make('_matrix_probe');
            } catch (\Throwable) {
                $matrix[] = [
                    'filter' => $shortName,
                    'state_type' => 'unknown',
                    'fields' => [],
                    'capabilities' => [],
                    'database_support' => [],
                    'limitations' => [],
                ];

                continue;
            }

            if (! method_exists($filter, 'getStateDescriptor')) {
                $matrix[] = [
                    'filter' => $shortName,
                    'state_type' => 'unknown',
                    'fields' => [],
                    'capabilities' => [],
                    'database_support' => [],
                    'limitations' => [],
                ];

                continue;
            }

            $descriptor = $filter->getStateDescriptor();

            $matrix[] = [
                'filter' => $shortName,
                'state_type' => $descriptor->getType()->value,
                'fields' => $descriptor->getFields(),
                'capabilities' => $descriptor->getCapabilities(),
                'database_support' => $descriptor->getDatabaseSupport(),
                'limitations' => $descriptor->getLimitations(),
            ];
        }

        return $matrix;
    }

    protected function formatMarkdown(array $matrix): string
    {
        $lines = [
            '# Filter Capability Matrix',
            '',
            '> Auto-generated by `php artisan dcat-filters:matrix`',
            '',
            '| Filter | State Type | Fields | Relationship | Multiple | Indicator | Database Support | Limitations |',
            '|--------|-----------|--------|:------------:|:--------:|:---------:|----------------|-------------|',
        ];

        foreach ($matrix as $row) {
            $caps = $row['capabilities'];
            $relationship = in_array('relationship', $caps) ? '✓' : '—';
            $multiple = in_array('multiple', $caps) ? '✓' : '—';
            $indicator = in_array('indicator', $caps) ? '✓' : '—';
            $fields = implode(', ', $row['fields']) ?: '—';
            $dbSupport = implode(', ', $row['database_support']) ?: '—';
            $limitations = implode('; ', $row['limitations']) ?: '—';

            $lines[] = "| {$row['filter']} | {$row['state_type']} | {$fields} | {$relationship} | {$multiple} | {$indicator} | {$dbSupport} | {$limitations} |";
        }

        $lines[] = '';

        return implode("\n", $lines);
    }
}
